routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ClientController@acceuil')->name('/');
Route::get('/contact', 'ClientController@contact')->name('page_contact');
Route::get('/prestataire/{id}', 'ClientController@prestataire')->name('page_prestataire');
Route::get('/ville/{nom}', 'ClientController@ville')->name('page_ville');
Route::get('/categorie/{nom}', 'ClientController@categorie')->name('page_categorie');
Route::get('/devenir', 'ClientController@devenirFreelancer')->name('page_devenir');
Route::post('/creerClient', 'ClientController@creerClient')->name('creer_client');

Route::prefix('client')->name('client.')->group(function () {
    Route::post('/ajouter/commentaire', 'ClientController@ajouterCommentaire')->name('ajouter_commentaire');
    Route::post('/Envoyer/contact', 'ClientController@envoyerMessage')->name('envoyer_contact');
    Route::post('/rechercher/accueil', 'ClientController@rechercheAccueil')->name('rechercher_accueil');
    Route::post('/rechercher/prestataire', 'ClientController@rechercherPrestataire')->name('rechercher_prestataire');
    Route::get('/count/clickContact/{id}', 'ClientController@clickContact')->name('click_contact');
    Route::get('/chercher/souscompetence/{id}', 'ClientController@chercherSousCategorie')->name('sous_categorie_client');

});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/config/admin', 'AdminController@index')->name('accueil_admin');
    Route::post('/config/ajouterAdmin', 'AdminController@ajouterAdmin')->name('ajouter_admin');
    Route::get('/config/AjouterAdministrateur', 'AdminController@compteAdmin')->name('config_administration');
    Route::get('/config/supprimerAdmin/{id}', 'AdminController@supprimerAdmin')->name('supprimer_admin');
    Route::get('/config/categorie', 'AdminController@acceuilCategorie')->name('config_categorie');
    Route::post('/config/ajouterCategorie', 'AdminController@ajouterCategorie')->name('ajouter_categorie');
    Route::get('/config/supprimerCategorie/{id}', 'AdminController@supprimerCategorie')->name('supprimer_categorie');
    Route::get('/config/prestataire', 'AdminController@prestataire')->name('config_prestataire');
    Route::get('/config/desactiverPrestataire/{user_id}/{value}', 'AdminController@desactiverPrestataire')->name('descativer_prestataire');
    Route::post('/config/ajouterPrestataire', 'AdminController@ajouterPrestataire')->name('ajouter_prestataire');
    Route::get('/config/supprimerPrestataire/{id}/{user_id}', 'AdminController@supprimerPrestataire')->name('supprimer_prestataire');
    Route::get('/config/commentaire', 'AdminController@commentaire')->name('config_commentaire');
    Route::get('/config/supprimerCommentaire/{id}', 'AdminController@supprimerCommentaire')->name('supprimer_commentaire');
});

Route::prefix('prestataires')->name('prestataires.')->group(function () {
    Route::get('/accueil/{id}', 'PrestataireController@index')->name('accueil');
    Route::get('/profil/{id}', 'PrestataireController@profilPrestataire')->name('profil');
    Route::post('/modifier/profil', 'PrestataireController@modifierProfil')->name('modifier_profil');
    Route::get('/competence/{id}', 'PrestataireController@competence')->name('competence');
    Route::get('/chercher/souscompetence/{id}', 'PrestataireController@chercherSousCategorie')->name('sous_categorie');
    Route::post('/ajouter/competence', 'PrestataireController@ajouterCompetence')->name('ajouter_competence');
    Route::get('/supprimer/competence/{categories_id}/{prestataire_id}/{id}', 'PrestataireController@supprimerCompetence')->name('supprimer_competence');
    Route::get('/entreprise/{id}', 'PrestataireController@entreprise')->name('entreprise');
    Route::post('/ajouter/entreprise', 'PrestataireController@ajouterEntreprise')->name('ajouter_entreprise');
    Route::get('/supprimer/entreprise/{entreprise_id}', 'PrestataireController@supprimerEntreprise')->name('supprimer_entreprise');
    Route::get('/realisation/{id}/{titre_categ}/{categorie_id}', 'PrestataireController@realisation')->name('realisation');
    Route::post('ajouter/realisation', 'PrestataireController@ajouterRealisation')->name('ajouter_realisation');
    Route::get('/supprimer/realisation/{id}', 'PrestataireController@supprimerRealisation')->name('supprimer_realisation');
    Route::post('modifier/banniere', 'PrestataireController@uploadBanner')->name('modifier_banner');

});

app/Models/Client.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'user_id',
        'nom',
        'prenom',
        'email',
        'telephone'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function commentaire()
    {
        return $this->hasMany(Commentaire::class);
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }
}

resources/views/admin/administration.blade.php
@extends('layouts.app')

@section('css')
@endsection
@section('title')
<i class="icon-material-outline-supervisor-account"></i>Comptes -- Administrateur
@endsection

@section('subtitle')
    Gestion Des Comptes
@endsection

@section('menu')
    Comptes
@endsection

@section('content')
<div class="row">

    <!-- Dashboard Box -->
    <div class="col-xl-12">
        <div class="dashboard-box margin-top-0">

            <!-- Headline -->
            <div class="headline">

                    <div id="message">
                        <a href="#sign-in-dialog" class="button popup-with-zoom-anim log-in-button"><i
                            class="icon-feather-plus"></i>
                        Ajouter un Administrateur</a>
                    </div>
            </div>

            <div class="content pb-2">
                <table class=" basic-table mb-5 container mt-5" id="example">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center" scope="col">id</th>
                            <th class="text-center" scope="col">Nom</th>
                            <th class="text-center" scope="col">Email</th>
                            <th class="text-center" scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr  id="user_{{ $user->id }}">
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    <button class="button red" onclick="supprimerAdmin({{ $user->id }})"><i class="icon-feather-trash-2"></i></button>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

    <div class="dashboard-footer-spacer"></div>

    <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

        <!--Tabs -->
        <div class="sign-in-form">

            <ul class="popup-tabs-nav">
                <li><a href="#register">Ajouter un Administrateur</a></li>
            </ul>

            <div class="popup-tabs-container">

                <!-- Register -->
                <div class="popup-tab-content" id="register">
                    <div id="notification"></div>

                    <!-- Welcome Text -->

                    <!-- Form -->
                    <form  id="ajout-admin-form">
                        @csrf
                        <div class="input-with-icon-left">
                            <i class="icon-feather-user"></i>
                            <input type="text" class="input-text with-border @error('name') is-invalid @enderror" placeholder="Votre Nom" name="name" value="{{ old('name') }}"  autocomplete="name" />
                            <span class="text-danger" id="name-error"></span>

                        </div>

                        <div class="input-with-icon-left">
                            <i class="icon-material-baseline-mail-outline"></i>
                            <input type="email" class="input-text with-border @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" placeholder="Adresse e-mail"  autocomplete="email"/>
                            <span class="text-danger" id="email-error"></span>
                            </div>

                        <div class="input-with-icon-left" title="Should be at least 8 characters long"
                            data-tippy-placement="bottom">
                            <i class="icon-material-outline-lock"></i>
                            <input type="password" class="input-text with-border @error('password') is-invalid @enderror" name="password"  placeholder="Mot de passe" autocomplete="new-password"/>
                            <span class="text-danger" id="password-error"></span>
                        </div>
                        <button class="margin-top-10 button full-width button-sliding-icon ripple-effect" type="submit"
                            >Ajouter <i
                                class="icon-material-outline-arrow-right-alt"></i></button>
                    </form>


                </div>

            </div>
        </div>
    </div>

@endsection
@section('script')
<script>
$.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#ajout-admin-form').submit(function(e) {
            e.preventDefault();
            let formData = new FormData(this);

            $('#name-error').text('');
            $('#email-error').text('');
            $('#password-error').text('');

            var notification = document.getElementById('notification')

            $.ajax({
                type: 'POST',
                url: "{{ route('admin.ajouter_admin') }}",
                data: formData,
                contentType: false,
                processData: false,
                success: (response) => {
                    if (response) {
                        console.log(response)
                        notification.innerHTML =
                            `<div class="notification success closeable mt-3">
                            <p> ${response.success} </p>
                            <a class="close" href="#"></a>
                        </div>`

                        $('table tbody').append(`
                                <tr id="user_${ response.users.id }">
                                <td>${ response.users.id }</td>
                                <td>${ response.users.name }</td>
                                <td>${ response.users.email }</td>
                                <td>
                                    <button class="button red" onclick="supprimerAdmin(${ response.users.id })"><i class="icon-feather-trash-2"></i></button>
                                </td>
                            </tr>
                        `)

                      //  this.reset();
                    }
                },
                error: function(response) {
                    console.log(response.responseJSON)
                    $('#name-error').text(response.responseJSON.errors.name);
                    $('#email-error').text(response.responseJSON.errors.email);
                    $('#password-error').text(response.responseJSON.errors.password);
                }
            });

        });
        function supprimerAdmin(id) {
           // var message = document.getElementById('message')

            url = "/admin/config/supprimerAdmin/" + id;

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $.ajax({
                type: "GET",
                url: url,
                success: function(response) {
                    if (response) {
                        $("#user_" + id).remove();
                        alert(response.success)
                    }
                }
            });
        }
</script>
@endsection

resources/views/admin/categorie.blade.php
@extends('layouts.app')

@section('css')
@endsection
@section('title')
    <i class="icon-material-outline-dashboard"></i> Catégories
@endsection

@section('subtitle')
    Gestion des catégories
@endsection

@section('menu')
    Catégories
@endsection

@section('content')
    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box margin-top-0">

                <!-- Headline -->
                <div class="headline">
                    <a href="#sign-in-dialog" class="button popup-with-zoom-anim log-in-button"><i
                            class="icon-feather-plus"></i>
                        Ajouter une catègorie</a>

                </div>

                <div class="content" >
                    <ul class="dashboard-box-list">
                        @foreach ($categories as $categorie)
                            <li id="categorie_{{ $categorie->id }}" >
                                <!-- Job Listing -->
                                <div class="job-listing width-adjustment">

                                    <!-- Job Listing Details -->
                                    <div class="job-listing-details">

                                        <!-- Details -->
                                        <div class="job-listing-description">
                                            <h3 class="job-listing-title"><a href="#">{{ $categorie->titre }}</a></h3>
                                        </div>
                                    </div>
                                </div>

                                <!-- Task Details -->
                                @if (count($categorie->souscategorie)>0)
                                   <ul class="dashboard-task-info">
                                    <li>
                                        @foreach ($categorie->souscategorie as $souscategorie)
                                          <span class="dashboard-status-button green"> {{ $souscategorie->titre_sous_categorie }} </span>
                                        @endforeach
                                    </li>
                                </ul>
                                @endif

                                <!-- Buttons -->
                                <div class="buttons-to-right always-visible">
                                    <button onclick="supprimerCategorie({{ $categorie->id }})"
                                        class="button red ripple-effect ico" title="Cancel Bid"
                                        data-tippy-placement="top"><i class="icon-feather-trash-2"></i></button>
                                </div>
                            </li>
                        @endforeach


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard-footer-spacer"></div>

    <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

        <!--Tabs -->
        <div class="sign-in-form">

            <ul class="popup-tabs-nav">
                <li><a href="#login">Ajouter une catégorie</a></li>
            </ul>

            <div class="popup-tabs-container">

                <!-- Login -->
                <div class="popup-tab-content">
                    <div id="notification"></div>
                    <!-- Form -->

                    <div class="col-xl-12">
                        <div class="submit-field">
                            <h5>Nom de la catégorie</h5>
                            <input type="text" name="titre" id="titre" class="with-border"
                                placeholder="Titre de la catégorie">
                            <span class="text-danger" id="titre-error"></span>
                        </div>
                    </div>
                    <div class="col-xl-12">
                        <div class="submit-field">
                            <h5>Choisir une ou plusieurs sous-catégorie</h5>

                            <select id="sous_cat" name="sous_cat" style="height: 200px" multiple
                                data-selected-text-format="count > 1">
                                <option>Laravel</option>
                                <option>NodeJs</option>
                                <option>Spring Boot</option>
                                <option>Synfony</option>
                                <option>Flutter</option>
                                <option>Angular</option>
                                <option>ReactJs</option>
                                <option>React Native</option>
                                <option>Django</option>
                                <option>WordPress</option>
                            </select>
                        </div>
                    </div>


                    <!-- Button -->
                    <button onclick="ajouterCategorie()" class="button full-width button-sliding-icon ripple-effect">Ajouter
                        <i class="icon-material-outline-arrow-right-alt"></i></button>

                </div>

            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function ajouterCategorie() {
            var titre = $('#titre').val()
            $('#titre-error').text('');

            var sous_cat = $('#sous_cat').val()
            var notification = document.getElementById('notification')
            $.ajax({
                url: "{{ route('admin.ajouter_categorie') }}",
                type: "POST",
                contentType: 'application/x-www-form-urlencoded',
                data: {
                    "_token": '{{ csrf_token() }}',
                    titre: titre,
                    sous_cat: sous_cat
                },
                dataType: 'JSON',
                success: function(response) {
                    notification.innerHTML =
                            `<div class="notification success closeable mt-3">
                            <p> ${response.message} </p>
                            <a class="close" href="#"></a>
                        </div>`
                       window.location.reload();

                },
                error: function(err) {
                    $('#titre-error').text(err.responseJSON.errors.titre);
                }
            });
        }

        function supprimerCategorie(id) {

            url = "/admin/config/supprimerCategorie/" + id

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "GET",
                url: url,
                success: function(response) {
                    if (response) {
                        alert(response.success)
                        $("#categorie_" + id).remove();
                    }
                }
            });
        }
    </script>
@endsection

resources/views/admin/commentaire.blade.php
@extends('layouts.app')

@section('css')
@endsection
@section('title')
<i class="icon-material-outline-rate-review"></i> Commentaires
@endsection

@section('subtitle')
    Gestion Commentaires
@endsection

@section('menu')
    Commentaires
@endsection

@section('content')
<div class="row">

    <!-- Dashboard Box -->
    <div class="col-xl-12">
        <div class="dashboard-box margin-top-0">

            <!-- Headline -->
            <div class="headline">
                <span  class=" popup-with-zoom-anim log-in-button"><i class="icon-material-outline-rate-review"></i>
                    Ajouter un prestataire</span>
                    <div id="message"></div>
            </div>

            <div class="content pb-2">
                <table class=" basic-table mb-5 container mt-5" id="example">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center" scope="col">Client</th>
                            <th class="text-center" scope="col">Email</th>
                            <th class="text-center" scope="col">Commentaire</th>
                            <th class="text-center" scope="col">Destinataire</th>
                            <th  scope="col">Posté le.</th>
                            <th class="text-center" scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($commentaires as $commentaire)
                            <tr id="commentaire_{{ $commentaire->id }}">
                                <td>{{ $commentaire->client->nom }}</td>
                                <td>{{ $commentaire->client->email }}</td>
                                <td> <p class="text-justify">{{ $commentaire->commentaire }}</p></td>
                                <td>{{ $commentaire->prestataire->nom }} {{ $commentaire->prestataire->prenom }}</td>
                                <td>{{ $commentaire->created_at }}</td>
                                <td>
                                    <button class="button red" onclick="supprimerCommentaire({{ $commentaire->id }})"><i class="icon-feather-trash-2"></i></button>
                                </td>

                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

    <div class="dashboard-footer-spacer"></div>

@endsection
@section('script')
<script>
    function supprimerCommentaire(id) {
            var message = document.getElementById('message')

            url = "/admin/config/supprimerCommentaire/" + id ;

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $.ajax({
                type: "GET",
                url: url,
                success: function(response) {
                    if (response) {
                        $("#commentaire_" + id).remove();
                        alert(response.success)
                    }
                }
            });
        }
</script>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('title')
    <i class="icon-line-awesome-dashboard"></i> Administration -- {{ Auth::user()->name }}
@endsection

@section('subtitle')
    Tableau de bord
@endsection

@section('menu')
    Accueil
@endsection


@section('content')
    <div class="fun-facts-container">
        <div class="fun-fact" data-fun-fact-color="#efa80f">
            <div class="fun-fact-text">
                <span>Prestataires</span>
                <h4> {{ $prestataire }}</h4>
            </div>
            <div class="fun-fact-icon"><i class="icon-line-awesome-street-view"></i></div>
        </div>
        <div class="fun-fact" data-fun-fact-color="#36bd78">
            <div class="fun-fact-text">
                <span>Clients</span>
                <h4>{{ $client }}</h4>
            </div>
            <div class="fun-fact-icon"><i class="icon-line-awesome-group
                "></i></div>
        </div>
        {{-- <div class="fun-fact" data-fun-fact-color="#b81b7f">
        <div class="fun-fact-text">
            <span>Réalisations</span>
            <h4>4</h4>
        </div>
        <div class="fun-fact-icon"><i class="icon-material-outline-business-center"></i></div>
    </div> --}}
        <!-- Last one has to be hidden below 1600px, sorry :( -->
        <div class="fun-fact" data-fun-fact-color="#2a41e6">
            <div class="fun-fact-text">
                <span>Catégories</span>
                <h4>{{ $categorie }}</h4>
            </div>
            <div class="fun-fact-icon"><i class="icon-line-awesome-inbox"></i></div>
        </div>
    </div>
@endsection