routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ClientController@acceuil')->name('/');
Route::get('/contact', 'ClientController@contact')->name('page_contact');
Route::get('/prestataire/{id}', 'ClientController@prestataire')->name('page_prestataire');
Route::get('/ville/{nom}', 'ClientController@ville')->name('page_ville');
Route::get('/categorie/{nom}', 'ClientController@categorie')->name('page_categorie');
Route::get('/devenir', 'ClientController@devenirFreelancer')->name('page_devenir');
Route::post('/creerClient', 'ClientController@creerClient')->name('creer_client');

Route::prefix('client')->name('client.')->group(function () {
    Route::post('/ajouter/commentaire', 'ClientController@ajouterCommentaire')->name('ajouter_commentaire');
    Route::post('/Envoyer/contact', 'ClientController@envoyerMessage')->name('envoyer_contact');
    Route::post('/rechercher/accueil', 'ClientController@rechercheAccueil')->name('rechercher_accueil');
    Route::post('/rechercher/prestataire', 'ClientController@rechercherPrestataire')->name('rechercher_prestataire');
    Route::get('/count/clickContact/{id}', 'ClientController@clickContact')->name('click_contact');
    Route::get('/chercher/souscompetence/{id}', 'ClientController@chercherSousCategorie')->name('sous_categorie_client');

});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/config/admin', 'AdminController@index')->name('accueil_admin');
    Route::post('/config/ajouterAdmin', 'AdminController@ajouterAdmin')->name('ajouter_admin');
    Route::get('/config/AjouterAdministrateur', 'AdminController@compteAdmin')->name('config_administration');
    Route::get('/config/supprimerAdmin/{id}', 'AdminController@supprimerAdmin')->name('supprimer_admin');
    Route::get('/config/categorie', 'AdminController@acceuilCategorie')->name('config_categorie');
    Route::post('/config/ajouterCategorie', 'AdminController@ajouterCategorie')->name('ajouter_categorie');
    Route::get('/config/supprimerCategorie/{id}', 'AdminController@supprimerCategorie')->name('supprimer_categorie');
    Route::get('/config/prestataire', 'AdminController@prestataire')->name('config_prestataire');
    Route::get('/config/desactiverPrestataire/{user_id}/{value}', 'AdminController@desactiverPrestataire')->name('descativer_prestataire');
    Route::post('/config/ajouterPrestataire', 'AdminController@ajouterPrestataire')->name('ajouter_prestataire');
    Route::get('/config/supprimerPrestataire/{id}/{user_id}', 'AdminController@supprimerPrestataire')->name('supprimer_prestataire');
    Route::get('/config/commentaire', 'AdminController@commentaire')->name('config_commentaire');
    Route::get('/config/supprimerCommentaire/{id}', 'AdminController@supprimerCommentaire')->name('supprimer_commentaire');
});

Route::prefix('prestataires')->name('prestataires.')->group(function () {
    Route::get('/accueil/{id}', 'PrestataireController@index')->name('accueil');
    Route::get('/profil/{id}', 'PrestataireController@profilPrestataire')->name('profil');
    Route::post('/modifier/profil', 'PrestataireController@modifierProfil')->name('modifier_profil');
    Route::get('/competence/{id}', 'PrestataireController@competence')->name('competence');
    Route::get('/chercher/souscompetence/{id}', 'PrestataireController@chercherSousCategorie')->name('sous_categorie');
    Route::post('/ajouter/competence', 'PrestataireController@ajouterCompetence')->name('ajouter_competence');
    Route::get('/supprimer/competence/{categories_id}/{prestataire_id}/{id}', 'PrestataireController@supprimerCompetence')->name('supprimer_competence');
    Route::get('/entreprise/{id}', 'PrestataireController@entreprise')->name('entreprise');
    Route::post('/ajouter/entreprise', 'PrestataireController@ajouterEntreprise')->name('ajouter_entreprise');
    Route::get('/supprimer/entreprise/{entreprise_id}', 'PrestataireController@supprimerEntreprise')->name('supprimer_entreprise');
    Route::get('/realisation/{id}/{titre_categ}/{categorie_id}', 'PrestataireController@realisation')->name('realisation');
    Route::post('ajouter/realisation', 'PrestataireController@ajouterRealisation')->name('ajouter_realisation');
    Route::get('/supprimer/realisation/{id}', 'PrestataireController@supprimerRealisation')->name('supprimer_realisation');
    Route::post('modifier/banniere', 'PrestataireController@uploadBanner')->name('modifier_banner');

});

app/Models/Prestataire.php
<?php

namespace App\Models;

use Carbon\Carbon;
use COM;
use Illuminate\Database\Eloquent\Model;

class Prestataire extends Model
{
    //
    protected $fillable = [
        'user_id',
        'nom',
        'prenom',
        'email',
        'age',
        'sexe',
        'ville',
        'quartier',
        'description',
        'telephone',
        'whatsapp',
        'file',
        'click',
        'click_contact',
        'banniere'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function categorie()
    {
        return $this
            ->belongsToMany(Categories::class, 'categories_prestataire')
            ->withPivot('id','prix_min','prix_max');;
    }

    public function entreprise()
    {
        return $this->hasMany(Entreprise::class);
    }

    public function commentaire()
    {
        return $this->hasMany(Commentaire::class);
    }
}

app/Http/Controllers/PrestataireController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use App\Models\Entreprise;
use App\Models\Prestataire;
use App\Models\Realisation;
use App\Models\Service;
use App\Models\SousCategorie;
use App\Models\User;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class PrestataireController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:PRESTATAIRE');
    }

    public function index($id)
    {
        try {
            $prestataire = Prestataire::where('user_id', $id)->firstOrFail();

            $click_prestataire = $prestataire->click;
            $competences = DB::table('categories_prestataire')->where('prestataire_id', '=', $prestataire->id)->count();
            $entreprises = Entreprise::where('prestataire_id', $prestataire->id)->count();


            return view('prestataire.home', compact('click_prestataire', 'competences', 'entreprises'));
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function profilPrestataire($id)
    {
        try {
            $users = User::find($id);
            $prestataire = Prestataire::where('user_id', $id)->firstOrFail();
            return view('prestataire.profil', compact('prestataire', 'users'));
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
        }
    }

    public function modifierProfil(Request $request)
    {
        try {
            if ($request->file) {
                $request->validate([
                    'file' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                ]);

                if ($request->file('file')) {
                    $image = $request->file('file');
                    $input['file'] = time() . '.' . $image->getClientOriginalExtension();
                    $imgFile = \Intervention\Image\Facades\Image::make($image->getRealPath());
                    $imgFile->save(public_path('avatars/' . $input['file']));
                }
                Prestataire::where('user_id', $request->user_id)->update(array(
                    'nom' => $request->nom,
                    'prenom' => $request->prenom,
                    'email' => $request->email,
                    'age' => $request->age,
                    'sexe' => $request->sexe,
                    'ville' => $request->ville,
                    'quartier' => $request->quartier,
                    'description' => $request->description,
                    'telephone' => $request->telephone,
                    'whatsapp' => $request->whatsapp,
                    // 'taux_horaire' => $request->taux_horaire,
                    'file' => $input['file']
                ));
                dd($input['file']);
            } else {
                $prestat =  Prestataire::where('user_id', $request->user_id)->update(array(
                    'nom' => $request->nom,
                    'prenom' => $request->prenom,
                    'email' => $request->email,
                    'age' => $request->age,
                    'sexe' => $request->sexe,
                    'ville' => $request->ville,
                    'quartier' => $request->quartier,
                    'description' => $request->description,
                    'telephone' => $request->telephone,
                    'whatsapp' => $request->whatsapp,
                    // 'taux_horaire' => $request->taux_horaire,

                ));
                dd("ffd");
            }

            return response()->json(['message' => 'Votre profil a été mise a jour avec succé'], 200);
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
            return response()->json(['error' =>  $e->getMessage()], 500);
        }
    }

    public function competence($id)
    {
        try {

            $categories = Categories::with('prestataire')->with('souscategorie')->with('service')->get();
            $prestataire = Prestataire::where('user_id', $id)->firstOrFail()->id;

            return view('prestataire.competence', compact('categories', 'prestataire'));
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
            return response()->json(['error' =>  $e->getMessage()], 500);
        }
    }

    public function chercherSousCategorie($id)
    {
        try {
            $sousCategories = SousCategorie::where('categories_id', $id)->get();
            return response()->json(['array' =>  $sousCategories]);
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()], 500);
        }
    }

    public function ajouterCompetence(Request $request)
    {
        try {
            $prestataire = Prestataire::where('user_id', $request->user_id)->firstOrFail();
            $query = DB::table('categories_prestataire')->where('categories_id', '=', $request->categorie_id)->where('prestataire_id', '=', $prestataire->id)->get();

            if (count($query) > 0) {
                return response()->json(['warrning' =>  "Vous avez déja cette compétence !"]);
            } else {

                $id_competence =  DB::table('categories_prestataire')->insertGetId(

                    [
                        'categories_id' => $request->categorie_id,
                        'prestataire_id' => $prestataire->id,
                        'prix_min' => $request->prix_min,
                        'prix_max' => $request->prix_max,

                    ],

                );
                for ($i = 0; $i < count($request->sous_cat); $i++) {
                    for ($j = 0; $j < count($request->competences); $j++) {
                        if ($i == $j) {
                            Service::create([
                                'categories_id' => $request->categorie_id,
                                'cat_prest_id' => $id_competence,
                                'titreService' => $request->sous_cat[$i],
                                'niveau' => $request->competences[$j]
                            ]);
                        }
                    }
                }
            }
            //$categories = Categories::with('prestataire')->with('souscategorie')->get();

            return response()->json([
                'success' =>  "Compétence Définie!",
                'array' => $prestataire->id
            ]);
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function supprimerCompetence($categories_id, $prestataire_id, $id)
    {
        try {
            DB::table('categories_prestataire')->where('categories_id', '=', $categories_id)->where('prestataire_id', '=', $prestataire_id)->delete();
            Service::where('cat_prest_id', $id)->delete();
            return response()->json([
                'success' => "compétence supprimer avec succés",
            ]);
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function entreprise($id)
    {
        try {
            $prestataire = Prestataire::where('user_id', $id)->firstOrFail();
            $entreprises = Entreprise::where('prestataire_id', $prestataire->id)->get();
            return view('prestataire.entreprise', compact('entreprises'));
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function ajouterEntreprise(Request $request)
    {

        try {
            $prestataire = Prestataire::where('user_id', $request->user_id)->firstOrFail();

            $entreprise = new Entreprise();
            $entreprise->prestataire_id = $prestataire->id;
            $entreprise->nom = $request->nom;
            $entreprise->tache = $request->tache;
            $entreprise->date_publication =  $request->date_publication;
            $entreprise->contact =  $request->contact;
            $entreprise->temoignage =  $request->temoignage;
            $entreprise->save();

            return response()->json([
                'success' =>  "Entreprise ajouter",
                'array' => $entreprise->getRawOriginal()
            ]);
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function supprimerEntreprise($id)
    {
        try {
            Entreprise::find($id)->delete();
            return response()->json([
                'success' => "Entreprise supprimer avec succés",
            ]);
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function realisation($compt_id, $titre_categ, $categorie_id)
    {
        $realisations = Realisation::where('cat_prest_id', $compt_id)->get();
        return view('prestataire.realisation', compact('compt_id', 'titre_categ', 'categorie_id', 'realisations'));
    }

    public function ajouterRealisation(Request $request)
    {
        try {
            $request->validate([
                'file' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);
            if ($request->file('file')) {
                $image = $request->file('file');
                $input['file'] = time() . '.' . $image->getClientOriginalExtension();
                $imgFile = \Intervention\Image\Facades\Image::make($image->getRealPath());
                $imgFile->save(public_path('realisations/' . $input['file']));
            }

            $realisation = new Realisation();
            $realisation->categories_id = $request->categorie_id;
            $realisation->cat_prest_id = $request->compt_id;

resources/views/prestataire/competence.blade.php
@extends('layouts.app')

@section('title')
    <i class="icon-line-awesome-puzzle-piece"></i> Compétences
@endsection

@section('subtitle')
    Définir de nouvelle compétences
@endsection

@section('menu')
    Compétences
@endsection

@section('content')
    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box margin-top-0">

                <!-- Headline -->
                <div class="headline">
                    <a href="#sign-in-dialog" class="button popup-with-zoom-anim log-in-button"><i
                            class="icon-feather-plus"></i>
                        Nouvelle compétence</a>

                    <div id="message"></div>
                    <hr>
                    <div class="contenu">
                        <ul class="dashboard-box-list">


                            @foreach ($categories as $categorie)
                                @foreach ($categorie->prestataire as $prest)

                                    @if ($prest->user_id == Auth::user()->id)
                                        <li id="categorie_{{ $categorie->id }}">
                                            <!-- Overview -->
                                            <div class="freelancer-overview manage-candidates">
                                                <div class="freelancer-overview-inner">

                                                    <!-- Avatar -->
                                                    <div class="freelancer-avatar">
                                                        <a onclick="supprimerCompetence({{ $categorie->id }},{{ $prest->id }},{{ $prest->pivot->id }})"
                                                            class="button text-white red ripple-effect ico"
                                                            title="Supprimer" data-tippy-placement="top"><i
                                                                class="icon-feather-trash-2"></i></a>
                                                        <a href="{{ route('prestataires.realisation', [$prest->pivot->id, $categorie->titre, $categorie->id]) }}"
                                                            class="button  ripple-effect ico" title="Réalisations"
                                                            data-tippy-placement="top"><i
                                                                class="icon-material-outline-business-center"></i></a>
                                                    </div>

                                                    <!-- Name -->
                                                    <div class="freelancer-name">
                                                        <h4><a href="#">{{ $categorie->titre }} <img class="flag"
                                                                    src="images/flags/de.svg" alt="" title="Germany"
                                                                    data-tippy-placement="top"></a></h4>

                                                        <!-- Bid Details -->
                                                        {{-- <ul class="dashboard-task-info bid-info">
                                                            @foreach ($categorie->prestataire as $tarif)
                                                                <li><strong>{{ $prest->pivot->prix_min }}
                                                                        XAF</strong><span>Tarif Min</span></li>
                                                                <li><strong>{{ $prest->pivot->prix_max }}
                                                                        XAF</strong><span>Tarif Max</span></li>
                                                            @endforeach
                                                        </ul> --}}
                                                        <!-- Buttons -->
                                                        <div
                                                            class="buttons-to-right always-visible margin-top-25 margin-bottom-0">
                                                            @foreach ($categorie->service as $service)
                                                                @if ($prestataire == $prest->pivot->prestataire_id && $categorie->id == $prest->pivot->categories_id)

                                                                    <span
                                                                        class="dashboard-status-button green" style="width: 200px">{{ $service->titreService }}
                                                                        <div class="progress">
                                                                            <div class="progress-bar" role="progressbar" style="width: {{ $service->niveau }}0%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="10">{{ $service->niveau }}</div>
                                                                          </div>
                                                                    </span>

                                                                @endif
                                                            @endforeach
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>

                                    @endif

                                @endforeach
                            @endforeach
                        </ul>

                    </div>
                </div>
            </div>
        </div>

        <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">
            <!--Tabs -->
            <div class="sign-in-form">

                <ul class="popup-tabs-nav">
                    <li><a href="#login">Définir une compétence</a></li>
                </ul>

                <div class="popup-tabs-container">

                    <!-- Login -->
                    <div class="popup-tab-content">
                        <div id="notification"></div>

                        <!-- Form -->
                        <form method="post">
                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>Choisir une compétence</h5>
                                    <input type="hidden" id="user_id" value="{{ Auth::user()->id }}">
                                    <select class=" input-text with-border" id="titre" style="height: 55px">
                                        <option>-- Choisir --</option>
                                        @foreach ($categories as $categorie)
                                            <option value="{{ $categorie->id }}">{{ $categorie->titre }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="section-headline margin-bottom-12">
                                    <h5>Choisir vos services</h5>
                                </div>

                                <select id="sousCat" style="height: 100px" multiple data-selected-text-format="count > 1">
                                    <option>-- Choisir --</option>
                                </select>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="section-headline margin-top-25 margin-bottom-12">
                                    <h5>Prix Min</h5>
                                </div>
                                <input type="number" id="prixMin" placeholder="Prix Minimal">
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="section-headline margin-top-25 margin-bottom-12">
                                    <h5>Prix Max</h5>
                                </div>
                                <input type="number" id="prixMax" placeholder="Prix Maximal">
                            </div>
                        </form>

                        <button onclick="ajouterCompetence()" class="button full-width button-sliding-icon ripple-effect"
                            form="login-form">Ajouter <i class="icon-material-outline-arrow-right-alt"></i></button>
                    </div>

                </div>
            </div>
        </div>
    @endsection

    @section('script')
        <script>
            $(document).ready(function() {
                //afficher les sous catégorie


                $('#titre').on('change', function() {
                    if ($("#titre").val() != "") {
                        $.ajax({
                            url: '/prestataires/chercher/souscompetence/' + $("#titre").val(),
                            type: 'GET',
                            success: function(response) {
                                $("#sousCat").html('');
                                if (response.array) {
                                    response.array.forEach(element => {
                                        $("#sousCat").append('<option value="' + element
                                            .titre_sous_categorie + '">' + element
                                            .titre_sous_categorie + ' </option>')
                                    });
                                }
                            },
                            error: function(xhr) {
                                alert("Impossible de récupérer ces données");
                            }
                        });
                    }

                });
            })

            function ajouterCompetence() {
                var user_id = $('#user_id').val()
                var categorie_id = $('#titre').val()
                var sous_cat = $('#sousCat').val()
                var prix_min = $('#prixMin').val()
                var prix_max = $('#prixMax').val()
                var notification = document.getElementById('notification')
                let array = []
                for (let index = 0; index < sous_cat.length; index++) {
                    const element = sous_cat[index];
                    var competence = prompt("Entrer votre niveau de compétence de 1 à 10 sur : " + sous_cat[index], "");
                    array.push(competence)
                }
                $.ajax({
                    url: "{{ route('prestataires.ajouter_competence') }}",
                    type: "POST",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {
                        "_token": '{{ csrf_token() }}',
                        user_id: user_id,
                        categorie_id: categorie_id,
                        sous_cat: sous_cat,
                        prix_min: prix_min,
                        prix_max: prix_max,
                        competences: array
                    },
                    dataType: 'JSON',
                    success: function(response) {
                        if (response.warrning) { // when status code is 422, it's a validation issue

                            notification.innerHTML =
                                `<div class="notification warning closeable">
                            <p>${response.warrning}</p>
                            <a class="close" href="#"></a>
                        </div>`

                        } else if (response.success) {
                            notification.innerHTML =
                                `<div class="notification success closeable">
                            <p>${response.success}</p>
                            <a class="close" href="#"></a>
                        </div>`
                            console.log(response.array)
                            //$('.contenu').append(response.array)
                            window.location.reload();
                        }
                    },
                    error: function(err) {
                        notification.innerHTML = `
                        <div class="notification error closeable">
                            <p>La compétence choisi est incorrect !</p>
                            <a class="close" href="#"></a>
                        </div>
                        `
                    }
                });
            }

            function supprimerCompetence(categorie, prest, id) {
                var message = document.getElementById('message')

                url = "/prestataires/supprimer/competence/" + categorie + "/" + prest + "/" + id;

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "GET",
                    url: url,
                    success: function(response) {
                        if (response) {
                            message.innerHTML =
                                `<div class="notification success closeable  mt-3">
                            <p>${response.success}</p>
                            <a class="close" href="#"></a>
                        </div>`
                            $("#categorie_" + categorie).remove();
                        }
                    }
                });
            }
        </script>
    @endsection

resources/views/prestataire/home.blade.php
@extends('layouts.app')

@section('title')
<i class="icon-material-outline-dashboard"></i> Prestataire -- {{ Auth::user()->name }}
@endsection

@section('subtitle')
Tableau de bord
@endsection

@section('menu')
Home
@endsection

@section('content')
<div class="fun-facts-container">
    <div class="fun-fact" data-fun-fact-color="#efa80f">
        <div class="fun-fact-text">
            <span>Vues</span>
            <h4> {{ $click_prestataire }}</h4>
        </div>
        <div class="fun-fact-icon"><i class="icon-feather-eye"></i></div>
    </div>
    <div class="fun-fact" data-fun-fact-color="#36bd78">
        <div class="fun-fact-text">
            <span>Compétences</span>
            <h4>{{ $competences }}</h4>
        </div>
        <div class="fun-fact-icon"><i class="icon-line-awesome-puzzle-piece"></i></div>
    </div>
    {{-- <div class="fun-fact" data-fun-fact-color="#b81b7f">
        <div class="fun-fact-text">
            <span>Réalisations</span>
            <h4>4</h4>
        </div>
        <div class="fun-fact-icon"><i class="icon-material-outline-business-center"></i></div>
    </div> --}}
    <!-- Last one has to be hidden below 1600px, sorry :( -->
    <div class="fun-fact" data-fun-fact-color="#2a41e6">
        <div class="fun-fact-text">
            <span>Entreprises</span>
            <h4>{{ $entreprises }}</h4>
        </div>
        <div class="fun-fact-icon"><i class="icon-material-outline-business"></i></div>
    </div>
</div>
@endsection