routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ClientController@acceuil')->name('/');
Route::get('/contact', 'ClientController@contact')->name('page_contact');
Route::get('/prestataire/{id}', 'ClientController@prestataire')->name('page_prestataire');
Route::get('/ville/{nom}', 'ClientController@ville')->name('page_ville');
Route::get('/categorie/{nom}', 'ClientController@categorie')->name('page_categorie');
Route::get('/devenir', 'ClientController@devenirFreelancer')->name('page_devenir');
Route::post('/creerClient', 'ClientController@creerClient')->name('creer_client');

Route::prefix('client')->name('client.')->group(function () {
    Route::post('/ajouter/commentaire', 'ClientController@ajouterCommentaire')->name('ajouter_commentaire');
    Route::post('/Envoyer/contact', 'ClientController@envoyerMessage')->name('envoyer_contact');
    Route::post('/rechercher/accueil', 'ClientController@rechercheAccueil')->name('rechercher_accueil');
    Route::post('/rechercher/prestataire', 'ClientController@rechercherPrestataire')->name('rechercher_prestataire');
    Route::get('/count/clickContact/{id}', 'ClientController@clickContact')->name('click_contact');
    Route::get('/chercher/souscompetence/{id}', 'ClientController@chercherSousCategorie')->name('sous_categorie_client');

});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/config/admin', 'AdminController@index')->name('accueil_admin');
    Route::post('/config/ajouterAdmin', 'AdminController@ajouterAdmin')->name('ajouter_admin');
    Route::get('/config/AjouterAdministrateur', 'AdminController@compteAdmin')->name('config_administration');
    Route::get('/config/supprimerAdmin/{id}', 'AdminController@supprimerAdmin')->name('supprimer_admin');
    Route::get('/config/categorie', 'AdminController@acceuilCategorie')->name('config_categorie');
    Route::post('/config/ajouterCategorie', 'AdminController@ajouterCategorie')->name('ajouter_categorie');
    Route::get('/config/supprimerCategorie/{id}', 'AdminController@supprimerCategorie')->name('supprimer_categorie');
    Route::get('/config/prestataire', 'AdminController@prestataire')->name('config_prestataire');
    Route::get('/config/desactiverPrestataire/{user_id}/{value}', 'AdminController@desactiverPrestataire')->name('descativer_prestataire');
    Route::post('/config/ajouterPrestataire', 'AdminController@ajouterPrestataire')->name('ajouter_prestataire');
    Route::get('/config/supprimerPrestataire/{id}/{user_id}', 'AdminController@supprimerPrestataire')->name('supprimer_prestataire');
    Route::get('/config/commentaire', 'AdminController@commentaire')->name('config_commentaire');
    Route::get('/config/supprimerCommentaire/{id}', 'AdminController@supprimerCommentaire')->name('supprimer_commentaire');
});

Route::prefix('prestataires')->name('prestataires.')->group(function () {
    Route::get('/accueil/{id}', 'PrestataireController@index')->name('accueil');
    Route::get('/profil/{id}', 'PrestataireController@profilPrestataire')->name('profil');
    Route::post('/modifier/profil', 'PrestataireController@modifierProfil')->name('modifier_profil');
    Route::get('/competence/{id}', 'PrestataireController@competence')->name('competence');
    Route::get('/chercher/souscompetence/{id}', 'PrestataireController@chercherSousCategorie')->name('sous_categorie');
    Route::post('/ajouter/competence', 'PrestataireController@ajouterCompetence')->name('ajouter_competence');
    Route::get('/supprimer/competence/{categories_id}/{prestataire_id}/{id}', 'PrestataireController@supprimerCompetence')->name('supprimer_competence');
    Route::get('/entreprise/{id}', 'PrestataireController@entreprise')->name('entreprise');
    Route::post('/ajouter/entreprise', 'PrestataireController@ajouterEntreprise')->name('ajouter_entreprise');
    Route::get('/supprimer/entreprise/{entreprise_id}', 'PrestataireController@supprimerEntreprise')->name('supprimer_entreprise');
    Route::get('/realisation/{id}/{titre_categ}/{categorie_id}', 'PrestataireController@realisation')->name('realisation');
    Route::post('ajouter/realisation', 'PrestataireController@ajouterRealisation')->name('ajouter_realisation');
    Route::get('/supprimer/realisation/{id}', 'PrestataireController@supprimerRealisation')->name('supprimer_realisation');
    Route::post('modifier/banniere', 'PrestataireController@uploadBanner')->name('modifier_banner');

});

app/Models/Client.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'user_id',
        'nom',
        'prenom',
        'email',
        'telephone'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function commentaire()
    {
        return $this->hasMany(Commentaire::class);
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use App\Models\Client;
use App\Models\Commentaire;
use App\Models\ContactUs;
use App\Models\Entreprise;
use App\Models\Prestataire;
use App\Models\Realisation;
use App\Models\Service;
use App\Models\SousCategorie;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class ClientController extends Controller
{
    public function acceuil()
    {
        $vedettes = Prestataire::orderBy('click', 'desc')->limit(5)->get();
        $categories = Categories::with('souscategorie')->get();
        return view('client.home', compact('vedettes', 'categories'));
    }

    public function contact()
    {
        $categories = Categories::with('souscategorie')->get();
        return view('client.contact', compact('categories'));
    }

    public function prestataire($id)
    {
        try {
            $prestataires = Prestataire::where('id', $id)->with('entreprise')->get();
            $commentaires = Commentaire::where('prestataire_id', $id)->with('client')->get();
            $count_entreprise = Entreprise::where('prestataire_id', $id)->count();
            $categories = Categories::with('prestataire')->with('souscategorie')->with('service')->with('realisation')->get();
            $realisations = Realisation::where('cat_prest_id', 107)->get();
            Prestataire::where('id', $id)->update(array(
                'click' => $prestataires[0]->click + 1,
            ));
            // foreach ($categories as $key => $value) {
            //   foreach ($value->prestataire as $key => $value2) {
            //       if ($value2->id == 1) {
            //           dd($value2);
            //       }
            //   }
            // }
            // $commentaires = Prestataire::where('id', $id)->with('commentaire')->get();
            return view('client.prestataire', compact(
                'prestataires',
                'commentaires',
                'count_entreprise',
                'categories'
            ));
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
        }
    }

    public function ville($nom)
    {
        $categories = Categories::with('souscategorie')->get();
        $prestataires = Prestataire::where('ville', $nom)->paginate(8);
        // $prestataires = DB::table('categories_prestataire')
        //     ->join('prestataires', 'categories_prestataire.prestataire_id', '=', 'prestataires.id')
        //     ->get();
        return view('client.ville', compact('categories', 'prestataires'));
    }

    public function categorie($id)
    {

        try {
            $categories = Categories::with('souscategorie')->get();
            if ($id == 0) {
                $prestataires = Prestataire::paginate(8);

                return view('client.categories', compact('categories', 'prestataires'));
            }

            $prestataires = DB::table('categories_prestataire')
                ->join('prestataires', 'categories_prestataire.prestataire_id', '=', 'prestataires.id')
                ->where('categories_id', $id)
                ->paginate(8);

            return view('client.categories', compact('categories', 'prestataires',));
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
        }
    }
    public function devenirFreelancer()
    {
        $categories = Categories::with('souscategorie')->get();
        return view('client.freelancer', compact('categories'));
    }

    public function creerClient(Request $request)
    {
        try {
            $request->validate([
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
                'password' => ['required', 'string', 'min:8'],

            ]);

            $user = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'password' => Hash::make($request->password),
            ]);
            DB::table('role_user')->insert(
                [
                    [
                        'role_id' => "3",
                        'user_id' => $user->id
                    ],

                ]
            );
            return view('client.home');
        } catch (Exception $e) {
            return response()->json(['error' =>  $e->getMessage()]);
        }
    }

    public function ajouterCommentaire(Request $request)
    {
        try {

            request()->validate(
                [
                    'commentaire' => 'required',
                ],
                [
                    'commentaire.required' => 'Le champ commentaire est requis!',
                ]
            );
            $client = Client::where('user_id', $request->client_id)->firstOrFail();
            $commentaire =  Commentaire::create([
                'client_id' => $client->id,
                'commentaire' => $request->commentaire,
                'prestataire_id' => $request->prestataire_id
            ]);
            return response()->json([
                'array' => $commentaire
            ]);
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
            return response()->json(['errors' => $e->validator->getMessageBag()], 422);
        }
    }
    public function rechercheAccueil(Request $request)
    {
        try {
            $service = Service::where('categories_id', $request->id_categorie)->where('titreService', $request->service)->get();

            $categories = Categories::with('souscategorie')->get();

            if (count($service) < 0) {
                $ville = "Oupps...!!! Aucun resultat  pour cette recherche";
                return view('client.home', compact('categories', 'ville'));
            }

            foreach ($service as $key => $value) {

                $prestataires = DB::table('prestataires')
                    ->join('categories_prestataire', 'prestataires.id', '=', 'categories_prestataire.prestataire_id')
                    ->where('categories_id', $value->categories_id)
                    ->get();
            }
            if (empty($prestataires)) {
                $ville = "Oupps...!!! Aucun resultat  pour cette recherche";
                return view('client.home', compact('categories', 'ville'));
            } else {

                if ($request->ville) {

                    foreach ($prestataires as $key => $prestataire) {
                        $result = Prestataire::where([['ville', $request->ville]])->get();
                        foreach ($result as $key => $value) {
                            if ($value->id == $prestataire->prestataire_id) {
                                $results = Prestataire::where([['id', $prestataire->prestataire_id]])->get();
                            }
                        }
                    }
                } else {
                    $results = $prestataires;
                }

                $ville = $request->ville;
                return view('client.home', compact('categories', 'prestataires', 'ville', 'results'));
            }
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
        }
    }

    public function rechercherPrestataire(Request $request)
    {
        try {
            $service = Service::where('categories_id', $request->categories_id)->where('titreService', $request->service)->get();

            $categories = Categories::with('souscategorie')->get();

            if (count($service) < 0) {
                $reponse = "Oupps...!!! Aucun resultat  pour cette recherche";
                return view('client.categories', compact('categories', 'reponse'));
            }

            // $prix = explode(",", $request->prix);


            foreach ($service as $key => $value) {

                $results = DB::table('prestataires')
                    ->join('categories_prestataire', 'prestataires.id', '=', 'categories_prestataire.prestataire_id')
                    ->where('categories_id', $value->categories_id)
                    // ->whereBetween('prix_max', [$prix[0], $prix[1]])
                    ->paginate(8);
            }

            if (empty($results)) {
                $reponse = "Oupps...!!!  Aucun resultat  pour cette recherche";
                return view('client.categories', compact('categories', 'reponse'));
            } else {
                foreach ($results as $key => $prestataire) {
                    $result = Prestataire::where([['ville', $request->ville]])->get();
                    foreach ($result as $key => $value) {
                        if ($value->id == $prestataire->prestataire_id) {
                            $prestataires = Prestataire::where([['id', $prestataire->prestataire_id]])->paginate(8);
                        }
                    }
                }

                $reponse = "Résultats pour cette recherche";
                return view('client.categories', compact('categories', 'prestataires', 'reponse'));
            }
        } catch (Exception $e) {
            echo 'and the error is: ',  $e->getMessage(), "\n";
        }
    }

    public function envoyerMessage(Request $request)
    {
        try {
            $this->validate($request, [
                'name' => 'required',
                'email' => 'required|email',
                'phone' => 'required',
                'subject' => 'required',
                'message' => 'required'
            ]);

            ContactUs::create($request->all());

            Mail::send([], array(
                'name' => $request->get('name'),
                'email' => $request->get('email'),
                'phone' => $request->get('phone'),

resources/views/client/categories.blade.php
@extends('welcome')


@section('css')
{{-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> --}}
@endsection


@section('content')
    <div class="full-page-container">

        @include('client.includes.categorie.sidebar')
        @include('client.includes.categorie.content')


    </div>

@endsection


@section('script')

    <script>
            $(document).ready(function() {
                //afficher les sous catégorie


                $('#titre').on('change', function() {
                    if ($("#titre").val() != "") {
                        $.ajax({
                            url: '/client/chercher/souscompetence/' + $("#titre").val(),
                            type: 'GET',
                            success: function(response) {
                                $("#sousCat").html('');
                                if (response.array) {
                                    response.array.forEach(element => {
                                        $("#sousCat").append('<option value="' + element
                                            .titre_sous_categorie + '">' + element
                                            .titre_sous_categorie + ' </option>')
                                    });
                                }
                            },
                            error: function(xhr) {
                                alert("Impossible de récupérer ces données");
                            }
                        });
                    }

                });
            })
        // Snackbar for user status switcher
        $('#snackbar-user-status label').click(function() {
            Snackbar.show({
                text: 'Your status has been changed!',
                pos: 'bottom-center',
                showAction: false,
                actionText: "Dismiss",
                duration: 3000,
                textColor: '#fff',
                backgroundColor: '#383838'
            });
        });
    </script>

    <!-- Google Autocomplete -->
    <script>
        function initAutocomplete() {
            var options = {
                types: ['(cities)'],
                // componentRestrictions: {country: "us"}
            };

            var input = document.getElementById('autocomplete-input');
            var autocomplete = new google.maps.places.Autocomplete(input, options);
        }
    </script>

    <!-- Google API & Maps -->
    <!-- Geting an API Key: https://developers.google.com/maps/documentation/javascript/get-api-key -->
    <script src="https://maps.googleapis.com/maps/api/js?key=&libraries=places"></script>

@endsection

resources/views/client/contact.blade.php
@extends('welcome')


@section('css')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
@endsection


@section('content')

    <div id="titlebar" class="gradient">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <h2>Contact</h2>

                    <!-- Breadcrumbs -->
                    <nav id="breadcrumbs" class="dark">
                        <ul>
                            <li><a href="#">Accueil</a></li>
                            <li><a href="#">Pages</a></li>
                            <li>Contact</li>
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
    </div>


    <!-- Content
        ================================================== -->


    <!-- Container -->
    <div class="container">
        <div class="row">

            <div class="col-xl-12">
                <div class="contact-location-info margin-bottom-50">
                    <div class="contact-address">
                        <ul>
                            <li class="contact-address-headline">Notre bureau</li>
                            <li>425 Yaoundé Polytechnique, CM 93584</li>
                            <li>Télèphone (+237)655332183</li>
                            <li><a href="#">contact@afrik-solutions.com</a></li>
                            <li>
                                <div class="freelancer-socials">
                                    <ul class="footer-social-links">
                                        <li>
                                            <button class="button" type="submit"><i class="icon-brand-linkedin-in"></i>
                                            </button>

                                        </li>
                                        <li>
                                            <button class="button ml-2 mr-2" type="submit"><i
                                                    class="icon-brand-facebook-f  pt-5"></i>
                                            </button>
                                        </li>
                                        <li>
                                            <button class="button" type="submit"><i class="icon-brand-twitter"></i>
                                            </button>

                                        </li>

                                    </ul>
                                </div>
                            </li>
                        </ul>

                    </div>
                    <div id="single-job-map-container">
                        <div id="singleListingMap" data-latitude="37.777842" data-longitude="-122.391805"
                            data-map-icon="im im-icon-Hamburger"></div>
                        <a href="#" id="streetView">Vue sur la rue</a>
                    </div>
                </div>
            </div>

            <div class="col-xl-8 col-lg-8 offset-xl-2 offset-lg-2">

                <section id="contact" class="margin-bottom-60">
                    <h3 class="headline margin-top-15 margin-bottom-35">Des questions? N'hésitez pas à nous contacter!</h3>
                    @if (Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session::get('success') }}
                        </div>
                    @endif
                    <form method="post" action="{{ route('client.envoyer_contact') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-with-icon-left">
                                    <input class="with-border" name="name" type="text" id="name" placeholder="Votre nom" />
                                    <i class="icon-material-outline-account-circle"></i>
                                    @if ($errors->has('name'))
                                        <div class="alert alert-danger">
                                            {{ $errors->first('name') }}
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="input-with-icon-left">
                                    <input class="with-border" name="email" type="email" id="email"
                                        placeholder="Adresse e-mail"
                                        pattern="^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$" />
                                    <i class="icon-material-outline-email"></i>
                                    @if ($errors->has('email'))
                                        <div class="alert alert-danger">
                                            {{ $errors->first('email') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="input-with-icon-left">
                            <input class="with-border" name="phone" type="text" id="phone" placeholder="Télèphone" />
                            <i class="icon-feather-phone"></i>
                            @if ($errors->has('phone'))
                                <div class="alert alert-danger">
                                    {{ $errors->first('phone') }}
                                </div>
                            @endif
                        </div>
                        <div class="input-with-icon-left">
                            <input class="with-border" name="subject" type="text" id="subject" placeholder="Sujet" />
                            <i class="icon-material-outline-assignment"></i>
                            @if ($errors->has('subject'))
                                <div class="alert alert-danger">
                                    {{ $errors->first('subject') }}
                                </div>
                            @endif
                        </div>

                        <div>
                            <textarea class="with-border" name="message" cols="40" rows="5" id="comments"
                                placeholder="Message" spellcheck="true"></textarea>
                            @if ($errors->has('message'))
                                <div class="alert alert-danger">
                                    {{ $errors->first('message') }}
                                </div>
                            @endif
                        </div>

                        <input type="submit" class="submit button margin-top-15" id="submit" value="Soumettre un message" />

                    </form>
                </section>

            </div>

        </div>
    </div>

@endsection


@section('script')
    <script>
        $('#snackbar-user-status label').click(function() {
            Snackbar.show({
                text: 'Your status has been changed!',
                pos: 'bottom-center',
                showAction: false,
                actionText: "Dismiss",
                duration: 3000,
                textColor: '#fff',
                backgroundColor: '#383838'
            });
        });
    </script>

    <script src="{{ asset('js/infobox.min.js') }}"></script>
    <script src="{{ asset('js/markerclusterer.js') }}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=&libraries=places"></script>

    <script src="{{ asset('js/maps.js') }}"></script>

@endsection

resources/views/client/freelancer.blade.php
@extends('welcome')


@section('css')

@endsection


@section('content')
<div id="titlebar" class="gradient">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<h2>Devenir Expert Certifier</h2>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Accueil</a></li>
						<li><a href="#">Pages</a></li>
						<li>Freelancer</li>
					</ul>
				</nav>

			</div>
		</div>
	</div>
</div>
<div class="container">
    <div class="section padding-top-60 padding-bottom-75">
        <div class="container">
            <div id="contenu">
                <div class="sous-contenu1">
                    <img src="images/banner/pexels-canva-studio-3194519.jpg" style="border-radius: 20px" class="img-ab" width="1200em" height="420em" alt="">
                </div>
                <div  class="sous-contenu2 ml-4">
                    <div class="col-12 col-sm-12">
                        <p> <strong style="color: #2a41e8; font-size: 2em">Les ateliers Pratiques</strong></p>
                    </div>
                    <div class="col-12 col-sm-12" >
                    <p class="text-justify">
                        Le lorem ipsum est, en imprimerie,
                        une suite de mots sans signification
                        utilisée à titre provisoire pour calibrer
                        une mise en page, le texte définitif venant
                        remplacer le faux-texte dès qu'il est prêt
                        ou que la mise en page est achevée.
                        Généralement, on utilise un texte en faux
                        latin, le Lorem ipsum ou Lipsum.

                    </p>
                    </div>
                    <div class="col-6 col-sm-12 mt-3">
                        <a href="https://www.lesatelierspratiques.com" class="button" target="_blank">Visitez le site des ateliers pratiques</a>
                    </div>
                    <div class="col-6 col-sm-12">
                        <img src="{{ asset('images/images/logo Ateliers Pratiques-01.png') }}" width="200px"  alt="">
                    </div>
                </div>
            </div>
            {{-- <div class="row">
                <div class="col-6">
                </div>
                <div class="col-6">
                    <div class="col-6 col-sm-12">
                        <p> <strong style="color: #2a41e8; font-size: 2em">Les ateliers Pratiques</strong></p>
                    </div>
                    <div class="col-6 col-sm-12" >
                    <p class="text-justify">
                        Le lorem ipsum est, en imprimerie,
                        une suite de mots sans signification
                        utilisée à titre provisoire pour calibrer
                        une mise en page, le texte définitif venant
                        remplacer le faux-texte dès qu'il est prêt
                        ou que la mise en page est achevée.
                        Généralement, on utilise un texte en faux
                        latin, le Lorem ipsum ou Lipsum.

                    </p>
                    </div>
                    <div class="col-6 col-sm-12 mt-3">
                        <a href="https://www.lesatelierspratiques.com" class="button" target="_blank">Visitez le site des ateliers pratiques</a>
                    </div>
                    <div class="col-6 col-sm-12">
                        <img src="{{ asset('images/images/logo Ateliers Pratiques-01.png') }}" width="200px"  alt="">
                    </div>
                </div>
            </div> --}}
        </div>

    </div>

</div>
@endsection

@section('script')

@endsection

resources/views/client/home.blade.php
@extends('welcome')


@section('css')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

@endsection


@section('content')
@include('client.includes.accueil.banner')

@if(Session::has('error'))
<script type="text/javascript" >
    alert("{{ session()->get('error') }}");

</script>

@endif


@include('client.includes.accueil.list_prestataire')
@include('client.includes.accueil.most_visite')

@include('client.includes.accueil.popular_categorys')
@include('client.includes.accueil.about_us')
@include('client.includes.accueil.testimonial')
@include('client.includes.accueil.partner')
@endsection


@section('script')
<script>
    function rechercheAccueil() {
                var ville = $('#ville').val()
                var service = $('#service').val()
                var id_categorie = $('#id_categorie').val()

                $.ajax({
                    url: "{{ route('client.rechercher_accueil') }}",
                    type: "POST",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {
                        "_token": '{{ csrf_token() }}',
                        ville: ville,
                        service: service,
                        id_categorie: id_categorie
                    },
                    dataType: 'JSON',
                    success: function(response) {
                        if (response) { // when status code is 422, it's a validation issue

                        console.log(response)
                        }
                    },
                    error: function(err) {
                       console.log(err)
                    }
                });
            }
</script>
@endsection